/*
 * generated by Xtext 2.24.0
 */
package stateMachine.xtext.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import stateMachine.xtext.mydsl.ui.internal.MydslActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("stateMachine.xtext.mydsl.MyDsl");
	}

}
